# Form implementation generated from reading ui file 'qstorewidget.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 40, 251, 108))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelLogo = QtWidgets.QLabel(parent=self.layoutWidget)
        self.labelLogo.setObjectName("labelLogo")
        self.horizontalLayout.addWidget(self.labelLogo)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelDescription = QtWidgets.QLabel(parent=self.layoutWidget)
        self.labelDescription.setWordWrap(True)
        self.labelDescription.setObjectName("labelDescription")
        self.verticalLayout.addWidget(self.labelDescription)
        self.horizontalLayout_buttons = QtWidgets.QHBoxLayout()
        self.horizontalLayout_buttons.setObjectName("horizontalLayout_buttons")
        self.labelProp = QtWidgets.QLabel(parent=self.layoutWidget)
        self.labelProp.setObjectName("labelProp")
        self.horizontalLayout_buttons.addWidget(self.labelProp)
        self.pushButtonUninstall = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButtonUninstall.setObjectName("pushButtonUninstall")
        self.horizontalLayout_buttons.addWidget(self.pushButtonUninstall)
        self.pushButtonInstall = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.pushButtonInstall.setObjectName("pushButtonInstall")
        self.horizontalLayout_buttons.addWidget(self.pushButtonInstall)
        self.horizontalLayout_buttons.setStretch(0, 2)
        self.horizontalLayout_buttons.setStretch(1, 1)
        self.horizontalLayout_buttons.setStretch(2, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_buttons)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelLogo.setText(_translate("MainWindow", "Logo"))
        self.labelDescription.setText(_translate("MainWindow", "Description"))
        self.labelProp.setText(_translate("MainWindow", "Prop"))
        self.pushButtonUninstall.setText(_translate("MainWindow", "Uninstall"))
        self.pushButtonInstall.setText(_translate("MainWindow", "Install"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
