# https://www.redhat.com/en/blog/create-rpm-package
# https://rpm-packaging-guide.github.io/

- name: Packages need to be installed to build
  package:
    name:
      - rpmdevtools
      - rpmlint
      - rsync
    state: present

- name: Create the file tree
  file:
    path: /root/rpmbuild/{{item}}
    state: directory
  with_items:
    - BUILD
    - BUILDROOT
    - RPMS
    - SOURCES
    - SPECS
    - SRPMS

- name: Create buildroot
  file:
    path: /root/rpmbuild/BUILDROOT/{{item}}
    state: directory
  with_items:
    - opt/qstore/
    - opt/qstore/ansible
    - opt/qstore/http

- name: Copy to buildroot
  synchronize:
    src: "{{item[0]}}"
    dest: "/root/rpmbuild/BUILDROOT/{{item[1]}}"
  loop:
    - ['/qstore/qstore', 'opt/qstore/']
    - ['/qstore/qstore.conf', 'opt/qstore/']
    - ['/qstore/ansible/qstore-playbook.yml', 'opt/qstore/ansible/']
    - ['/qstore/ansible/qstore-systemd.yml', 'opt/qstore/ansible/']
    - ['/qstore/html/', 'opt/qstore/html/']

- name: Copy spec file
  template:
    src: qstore.spec.j2
    dest: /root/rpmbuild/SPECS/qstore.spec
