# https://www.redhat.com/en/blog/create-rpm-package
# https://rpm-packaging-guide.github.io/

- name: Packages need to be installed to build
  package:
    name:
      - rpmdevtools
      - rpmlint
    stare: present

- name: Create the file tree
  file:
    path: /root/rpmbuild/{{item}}
    state: directory
  with_items:
    - BUILD
    - BUILDROOT
    - RPMS
    - SOURCES
    - SPECS
    - SRPMS

- name: Create buildroot
  file:
    path: /root/rpmbuild/BUILDROOT/{{item}}
    state: directory
  with_items:
    - opt/qstore/
    - opt/qstore/ansible
    - opt/qstore/http