# https://www.redhat.com/en/blog/create-rpm-package
# https://rpm-packaging-guide.github.io/

- name: Packages need to be installed to build
  package:
    name:
      - rpmdevtools
      - rpmlint
      - rsync
    state: present

- name: Set facts env
  set_fact:
    ver: "{{lookup('ansible.builtin.env', 'VER')}}"
    ghw: "{{lookup('ansible.builtin.env', 'GHW')}}"

- name: Create the file tree
  file:
    path: /root/rpmbuild/{{item}}
    state: directory
  with_items:
    - BUILD
    - BUILDROOT
    - RPMS
    - SOURCES
    - SPECS
    - SRPMS

- name: Create buildroot
  file:
    path: /root/rpmbuild/BUILDROOT/{{item}}
    state: directory
  with_items:
    - qstore-{{ver}}/opt/qstore/
    - qstore-{{ver}}/opt/qstore/ansible
    - qstore-{{ver}}/opt/qstore/http

- name: Copy to buildroot
  synchronize:
    src: "{{ghw}}/{{item[0]}}"
    dest: "/root/rpmbuild/BUILDROOT/qstore-{{ver}}/{{item[1]}}"
  loop:
    - ['qstore', 'opt/qstore/']
    - ['qstore.conf', 'opt/qstore/']
    - ['ansible/qstore-playbook.yml', 'opt/qstore/ansible/']
    - ['ansible/qstore-systemd.yml', 'opt/qstore/ansible/']
    - ['html/', 'opt/qstore/html/']

- name: Copy spec file
  template:
    src: qstore.spec.j2
    dest: /root/rpmbuild/SPECS/qstore.spec

- name: Copy spec file
  command: tar -czf /root/rpmbuild/SOURCES/qstore-{{ver}}.tar.gz -C /root/rpmbuild/BUILDROOT .

- name: Lint spec file
  command: rpmlint /root/rpmbuild/SPECS/qstore.spec

- name: Build spec file
  command: rpmbuild -bb /root/rpmbuild/SPECS/qstore.spec