- name: Install binutils
  package:
    name:
      - python3-dev
      - python3-venv
      - binutils
    state: present
  when: ansible_os_family in ['Debian']

- name: Install binutils
  package:
    name:
      - python3-devel
      - binutils
    state: present
  when: ansible_os_family in ['RedHat', 'Rocky']

- name: Create venv
  command: python3 -m venv .venv

- name: Debian 10
  block:
    - name: Debian 10 build-essential
      command: apt -y install build-essential
    - name: Debian 10 pip
      command: .venv/bin/pip install --upgrade pip 
    - name: Debian 10 pyqt
      shell: .venv/bin/pip install pyqt6==6.5 pyinstaller
  when: ansible_os_family == 'Debian' and ansible_lsb.release == '10'

- name: Install in venv
  command: .venv/bin/pip install pyqt6 pyinstaller
  when: not (ansible_os_family == 'Debian' and ansible_lsb.release == '10')
  
- name: Create pkg
  command: .venv/bin/pyinstaller --hidden-import pyqt6.sip ../qstore.py
