- name: Install all
  package:
    name:
      - openbox
      - libxcb*
      - libxkbcommon*
      - binutils
    state: present

- name: Install deb
  package:
    name:
      - python3-dev
      - python3-venv
    state: present
  when: ansible_os_family in ['Debian']

- name: Install rpm
  package:
    name:
      - python3-devel
    state: present
  when: ansible_os_family in ['RedHat', 'Rocky']

- name: Create venv
  command: python3 -m venv .venv

- name: Debian 10
  block:
    - name: Debian 10 build-essential
      command: apt -y install build-essential
    - name: Debian 10 pip
      command: .venv/bin/pip install --upgrade pip setuptools
    - name: Debian 10 pyqt
      shell: .venv/bin/pip install pyqt6==6.5 pyinstaller requests
  when: ansible_os_family == 'Debian' and ansible_lsb.release == '10'

- name: Install in venv
  command: .venv/bin/pip install pyqt6 pyinstaller requests
  when: not (ansible_os_family == 'Debian' and ansible_lsb.release == '10')
  
- name: Create pkg
  command: .venv/bin/pyinstaller -F --hidden-import requests ../qstore.py

- name: Mv up
  command: mv dist/qstore ../
