name: debian-12

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types:
      - published

jobs:

  build:

    runs-on: ubuntu-latest
    container: debian:10
    timeout-minutes: 5

    steps:
    
      - uses: actions/checkout@v4
      - run: apt update
      - run: apt -y install ansible
      - run: /usr/bin/ansible-playbook ansible/build-deb.yml
      - run: tar -czf qstore-debian-12.tar.gz qstore post-server.py ansible/ html/
      
      - uses: actions/upload-artifact@v4
        with:
          name: qstore-debian-12.tar.gz
          path: qstore-debian-12.tar.gz

      - uses: actions/upload-release-asset@v1
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: qstore-debian-12.tar.gz
          asset_name: qstore-debian-12.tar.gz
          asset_content_type: application/gzip
            