name: debian-12

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:

    runs-on: ubuntu-latest
    container: debian:12
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
      - run: apt update
      - run: apt -y install ansible
      - run: /usr/bin/ansible-playbook ansible/build-deb.yml

      - uses: actions/upload-artifact@v4
        with:
          name: debian-12
          path: |
            ansible/dist/
            ansible/qstore-playbook.yml
            ansible/qstore-systemd.yml
            html/