name: ubuntu-24.04

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:
  
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    env:
      DEBIAN_FRONTEND: noninteractive

    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update
      - run: sudo apt -y install ansible
      - run: sudo /usr/bin/ansible-playbook ansible/build-deb.yml
      
      - uses: actions/upload-artifact@v4
        with:
          name: ubuntu-24.04
          path: |
            qstore
            ansible/qstore-playbook.yml
            ansible/qstore-systemd.yml
            html/
            post-server.py
