name: ubuntu-24.04

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:
  
    runs-on: ubuntu-24.04
    timeout-minutes: 5

    env:
      DEBIAN_FRONTEND: noninteractive

    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update
      - run: sudo apt -y install ansible
      - run: sudo /usr/bin/ansible-playbook ansible/build-deb.yml
      - run: tar -czf qstore-$GITHUB_WORKFLOW.tar.gz qstore post-server.py ansible/ html/
      
      - uses: actions/upload-artifact@v4
        with:
          name: qstore-$GITHUB_WORKFLOW.tar.gz
          path: qstore-$GITHUB_WORKFLOW.tar.gz

      - uses: actions/upload-release-asset@v1
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: qstore-$GITHUB_WORKFLOW.tar.gz
          asset_name: qstore-$GITHUB_WORKFLOW.tar.gz
          asset_content_type: application/gzip